### PR TITLE
fix Coq's PR 403

### PR DESCRIPTION
**Pull request by gares**

### CODE REVIEW

**Comment by ejgallego** [comment]
@gares can you rebase on top of the new PR?

**Comment by gares** [comment]
Sorry Emilio I'm not following.  What could I do?  Which new PR?

**Comment by ejgallego** [comment]
@gares I see lots of conflicts in the github interface but maybe it is a github bug? Let me check.

**Comment by gares** [comment]
oh, I see, I'll try to fix my mess

**Comment by ejgallego** [comment]
Yeah it was really my problem as I had to rebase the original tree, you should either rebase if you want, for now I've cherry-picked your patch, thanks!!!

**Pull request closed without merging**
