### PR TITLE
renaming "CAst.ast" to "CAst.t"

### PR DESCRIPTION
**Pull request by ghost**
From the two options:
- `CAst.ast`
- `CAst.t`

I consider the second one strictly better because it conveys less noise.

But, I guess, only people who are not yet desensitized to the noise would feel the difference.

### CODE REVIEW

**Comment by ejgallego** [comment]
Haven't made my mind on this one. What does the OCaml compiler use?

**Comment by ghost** [comment]
I've looked at [Parsetree](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Parsetree.html) and they do not try to go as far as you intend for the Coq AST (refactoring location out of variants). They have:
- [Location.t](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Location.html#TYPEt)
- ['a Location.loc](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Location.html#TYPEloc)

**Comment by ghost** [comment]
Although Parsetree is the part of the Ocaml project, where (while browsing the "documentation"), Google asked me whether I want to translate the text from "Telugu" to English. So I am not sure if this is a good role model...

**Comment by ejgallego** [comment]
Where are attributes stored, in the `txt` field of `'a loc` ?

**Comment by ghost** [comment]
Parsetree / signature / signature_item / Psig_value / value_description / pval_attributes / attributes / [attribute](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Parsetree.html#TYPEattribute)

**Comment by ejgallego** [comment]
Thanks @matejkosik , I see OCaml has evolved a bit and they are more generic thou not fully
https://github.com/ocaml/ocaml/blob/trunk/parsing/parsetree.mli

Maybe this is necessary. I am inclined towards taking this PR, however I'd like to hear some more opinions.

**Comment by ejgallego** [comment]
@matejkosik, in case you are interested I was planning to merge your PR, once the Coq PR situation was clarified.

**Comment by ghost** [comment]
Ok.

**Comment by ejgallego** [comment]
Thanks!

**Comment by ejgallego** [comment]
merged thanks!

**Pull request closed without merging**
