### PR TITLE
Coqdoc

### PR DESCRIPTION
**Pull request by gares**
--header and --footer should be castomizeable.  I've also removed spurious <p> tags.  BTW, you may be interested in this header/footer code that adds load/save buttons
  https://github.com/gares/cws16
here how it looks like
  http://www-sop.inria.fr/teams/marelle/advanced-coq-16/test.html

Best,

### CODE REVIEW

**Comment by ejgallego** [comment]
Hi Enrico,

thanks for this! I've cherry picked the header/footer fixes (note that I rebase vs v8.5 so you may need to rebase/force pull against my branch too).

I'm not sure about 8d013e6 thou, see the note in the commit.

Thanks for the save/load code, we'll try to integrate it.

**Comment by gares** [comment]
Hi.  Because it was not properly balanced (missing </p>) and this was causing layout troubles IIRC.

**Comment by gares** [comment]
< / p >

that is the missing thing

**Comment by ejgallego** [comment]
I see thanks!

Note that`</p>` tags are not required in Html5 (except for a few cases).

The original code was trying to honor coqdoc's intention to open a paragraph, and I'd like to keep it if possible.

How can the layout problems be reproduced? Will the school files do the trick? There may be a bug in the header as we claim the file to the xhtml (where indeed `</p>` is required) but if that's the problem I'd rather switch to html5.

Thanks, E.

**Pull request closed without merging**
